# Generated by Django 2.2.1 on 2019-05-10 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import map.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_layer', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('select_theme', models.CharField(choices=[('CEN', 'Census'), ('EDU', 'Education'), ('RUL', 'Rural'), ('WAT', 'Water'), ('HEL', 'Health'), ('OTH', 'Other')], default='Census', max_length=6)),
                ('if_other', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('types', models.CharField(choices=[('GJ', 'GeoJSON'), ('EL', 'Excel'), ('CV', 'CSV'), ('GL', 'GML'), ('ZS', 'Zipped Shapefile'), ('KL', 'KML'), ('PF', 'PDF'), ('TF', 'TIF'), ('PG', 'PNG'), ('JG', 'JPEG')], default='Zipped Shapefile', max_length=6)),
                ('style_file_available', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Yes', max_length=2)),
                ('tool_used', models.CharField(max_length=50)),
                ('layer', models.FileField(upload_to=map.models.user_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
