# Generated by Django 2.2.1 on 2019-05-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190510_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layers',
            name='style_file_available',
            field=models.CharField(choices=[('NON', 'None'), ('Y', 'Yes'), ('N', 'No')], default='None', max_length=3),
        ),
    ]
