# Generated by Django 2.2.1 on 2019-06-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190611_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
