# Generated by Django 2.2.1 on 2019-06-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0004_customimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpages',
            name='image',
        ),
        migrations.AddField(
            model_name='postpages',
            name='post_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
