# Generated by Django 2.2.1 on 2019-06-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190611_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpages',
            name='author',
        ),
    ]
